version: '3.1'

services:
  
  marketplace-db:
    container_name: marketplace_postgres
    image: 'postgres:15'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: kica
      POSTGRES_PASSWORD: kica
    volumes:
      - marketplace-db:/var/lib/postgresql/data
      
volumes:
  
  marketplace-db:
    external: true